# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec4afea823056f3fa2b4ad84676fdc559eced1406d151ec6917273579693a494f1e5efcc934b1ac9876422458872bfee6e24597e353eec1769f26a70a2d49933

test:
  secret_key_base: b4e91191db6bad798b9066374fe8064a7874020517cccfed7dde3bb9daacc086a2100b2132e471666958f5b7ce4cda01bdad2567e5badedc70874cebf83d8da3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
